#!/usr/bin/env python3
import sys
import time

_, nproc, path = sys.argv[:3]

with open(path) as f:
    unsorted = [int(x) for x in f]

start = time.time()
res = sorted(unsorted)
end = time.time()
print('QuickSort: {0}'.format(int((end - start) * 1000000)))
for x in res:
    print(x)
